services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./boutique-en-ligne:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_SERVER: mysql
      MYSQL_USER: axel
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: boutique_en_ligne
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_ARBITRARY: 1


